# Generated by Django 4.2.7 on 2024-01-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
