# Generated by Django 4.2.7 on 2024-01-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_product_remove_order_user_delete_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
