# Generated by Django 4.2.7 on 2024-02-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
