# Generated by Django 4.2.7 on 2024-01-29 08:52

import apps.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_remove_order_product_remove_order_user_delete_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('invoiced', 'Invoiced'), ('shipped', 'Shipped'), ('delivered', 'delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='initiated', max_length=10)),
                ('shipping_amount', apps.core.fields.AmountField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_amount', apps.core.fields.AmountField(decimal_places=2, default=0.0, max_digits=8)),
                ('sub_total', apps.core.fields.AmountField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', apps.core.fields.AmountField(decimal_places=2, default=0.0, max_digits=8)),
                ('shipping_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('per_price', apps.core.fields.AmountField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', apps.core.fields.AmountField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
