# Generated by Django 5.1 on 2024-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contact',
            field=models.CharField(),
        ),
    ]
