# Generated by Django 4.1.7 on 2023-11-05 12:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Main', 'Main'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('service', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.service')),
            ],
        ),
    ]
