# Generated by Django 4.1.7 on 2023-10-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_contact_us_email_alter_contact_us_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.service'),
        ),
    ]
